---
- name: install apache httpd
  yum: name=httpd state=installed
  tags:
    - httpd
    - packages

- name: install mod_ssl
  yum: name=mod_ssl state=installed
  when: httpd_mod_ssl == true
  tags:
    - httpd
    - packages

- name: configure firewalld for httpd
  firewalld: zone=public service={{ item }} permanent=true state=enabled
  with_items:
    - http
    - https
  when: ansible_distribution_major_version|int > 6
  notify: reload firewall
  tags:
    - httpd
    - firewall
    - configuration
