---
- name: install apache httpd
  yum: name=httpd state=installed
  tags:
    - httpd
    - packages

- name: install mod_ssl
  yum: name=mod_ssl state=installed
  when: httpd_mod_ssl == true
  tags:
    - httpd
    - packages

- name: configure httpd
  template: src="httpd.conf.{{ ansible_os_family }}{{ ansible_distribution_major_version }}.j2" dest=/etc/httpd/conf/httpd.conf mode=0644 owner=root group=root
  notify: restart httpd

- name: configure firewalld for httpd
  firewalld: zone=public service={{ item }} permanent=true state=enabled
  with_items:
    - http
    - https
  when: ansible_distribution_major_version|int > 6
  notify: reload firewall
  tags:
    - httpd
    - firewall
    - configuration
