---
- name: install apache httpd
  yum: name=httpd state=installed
  tags:
    - httpd
    - packages

- name: install mod_ssl
  yum: name=mod_ssl state=installed
  when: httpd_mod_ssl == true
  tags:
    - httpd
    - ssl
    - packages

- name: install private keys
  copy: content="{{ item.private_key }}" dest="/etc/pki/tls/private/{{ item.servername }}.key" owner=root group=root mode=0600
  with_items: httpd_vhosts
  when: item.private_key is defined
  no_log: true
  tags:
    - httpd
    - ssl
    - configuration

- name: install certificates
  copy: content="{{ item.certificate }}" dest="/etc/pki/tls/certs/{{ item.servername }}.crt" owner=root group=root mode=0644
  with_items: httpd_vhosts
  when: item.private_key is defined
  no_log: true
  tags:
    - httpd
    - ssl
    - configuration

- name: install certificate chains
  template: src=chain.pem.j2 dest="/etc/pki/tls/certs/{{ item.servername }}.chain.crt" owner=root group=root mode=0644
  with_items: httpd_vhosts
  when: item.chain is defined
  no_log: true
  tags:
    - httpd
    - ssl
    - configuration

- name: configure httpd.conf
  template: src="httpd.conf.{{ ansible_os_family }}{{ ansible_distribution_major_version }}.j2" dest=/etc/httpd/conf/httpd.conf mode=0644 owner=root group=root
  notify: restart httpd
  tags:
    - httpd
    - configuration

- name: configure modules
  template: src="{{ item }}.j2" dest="/etc/httpd/conf.modules.d/{{ item }}" owner=root group=root mode=0644
  with_items:
    - 00-mpm.conf
    - 00-ssl.conf
  when: ansible_distribution_major_version|int > 6
  notify: restart httpd
  tags:
    - httpd
    - configuration

- name: configure conf.d
  template: src="{{ item }}.j2" dest="/etc/httpd/conf.d/{{ item }}" owner=root group=root mode=0644
  with_items:
    - ssl.conf
  notify: restart httpd
  tags:
    - httpd
    - configuration

- name: configure firewalld for httpd
  firewalld: zone=public service={{ item }} permanent=true state=enabled
  with_items:
    - http
    - https
  when: ansible_distribution_major_version|int > 6
  notify: reload firewall
  tags:
    - httpd
    - firewall
    - configuration

- name: allow httpd connect db
  seboolean: name=httpd_can_network_connect_db state={{ httpd_can_network_connect_db }} persistent=yes
  when: ansible_selinux.status == 'enabled'
  tags:
    - httpd
    - selinux
    - configuration

- name: allow httpd connect
  seboolean: name=httpd_can_network_connect state={{ httpd_can_network_connect }} persistent=yes
  when: ansible_selinux.status == 'enabled'
  tags:
    - httpd
    - selinux
    - configuration

- name: ensure httpd is enabled and running
  service: name=httpd enabled=yes state=started
  tags:
    - httpd
    - configuration
    - services
